### ISSUE TITLE
Is it possible to add Web Directory as media source

### ISSUE THREAD

**Issue by atmos-o** [EsTass/phpmediaserver#7]
I have a web directory with media arranged in the same way Plex and the other media servers advise to arrange it, would I be able to use that as a source for my media? I have the video, subtitle, poster & other images all in the same directory level.
Example of how it looks

`/movies`
`___ /"Movie Name"`
`_______ /video.mp4`
`_______ /subtitle.vtt`
`_______ /poster.jpg`

**Comment by EsTass** [comment]
With the valid permissions so that php can access the folder it can perfectly for the videos (tested with nfs, samba and sshfs). If you have access to read the folder it can be used.

The title is extracted from the file itself or the folder that contains it, testing both in the detection. The poster is obtained from the detection itself, it would not use the "poster.png". The subtitles are only obtained from the video itself if it has them embedded as in mkv formats for example.

To reuse the "poster.xxx" files you can make a script that will move them to the "cache / mediadata" folder and give it the "title.xxx" so it would use them. If in the detection it does not add the poster, it still tries to look for a new one in the content updates externally until it finds it.

The subtitles there is no way to add them externally to the video "cache", just only use the embedded ones.

**Comment by atmos-o** [comment]
So to clarify, I can point it to my web directory such as `https://web.dir.com/movies` & it will be able to to find it all?

**Comment by EsTass** [comment]
Not tested but scandir cant  list content of http url folder, can try mounting web folder first with webdav to system folder and select this folder for scan. I have tested with sshfs, samba and nfs mounted on folder and have no problems scanning and playing, never tested with webdav sorry.
